name = "Carpet"
filename = "fabric-carpet-1.17.1-1.4.49+v211021.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3497/750/fabric-carpet-1.17.1-1.4.49+v211021.jar"
hash-format = "murmur2"
hash = "1134493222"

[update]
[update.curseforge]
file-id = 3497750
project-id = 349239
release-channel = "beta"
