name = "Carpet"
filename = "fabric-carpet-1.17.1-1.4.52+v211104.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3514/689/fabric-carpet-1.17.1-1.4.52+v211104.jar"
hash-format = "murmur2"
hash = "3926103005"

[update]
[update.curseforge]
file-id = 3514689
project-id = 349239
release-channel = "beta"
