name = "Carpet Extra"
filename = "carpet-extra-1.17.1-1.4.51.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3507/194/carpet-extra-1.17.1-1.4.51.jar"
hash-format = "murmur2"
hash = "2189147937"

[update]
[update.curseforge]
file-id = 3507194
project-id = 349240
release-channel = "beta"
