name = "Carpet"
filename = "fabric-carpet-1.17.1-1.4.44+v210714.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3388/180/fabric-carpet-1.17.1-1.4.44+v210714.jar"
hash-format = "murmur2"
hash = "2935398146"

[update]
[update.curseforge]
file-id = 3388180
project-id = 349239
release-channel = "beta"
