name = "Lithium"
filename = "lithium-fabric-mc1.17.1-0.7.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.17.1-0.7.4/lithium-fabric-mc1.17.1-0.7.4.jar"
hash-format = "sha512"
hash = "e3564bef105f23b6d4f77196f080f6bae3eed78b810e795c41b6587e88130ead66d0bbc01225a2ca2a3b1bdaedd7baec35219e28e36b3fe5c7a9b694618dfc76"

[update]
[update.modrinth]
mod-id = "gvQqBUqZ"
version = "nVR7Q63z"
