name = "Mod Menu"
filename = "modmenu-2.0.4.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/mOgUt4GM/versions/2.0.4/modmenu-2.0.4.jar"
hash-format = "sha512"
hash = "65ea03ce8e5863840007e37128bd6e15c0c632b67eae10ef5fb722e355ae82e512b52b8d15fb254a4509b5879d0b431fa74f99f1d0773c4bbff58df98b6dea3d"

[update]
[update.modrinth]
mod-id = "mOgUt4GM"
version = "oQr5VO7q"
