name = "Sodium Extra"
filename = "sodium-extra-mc1.17.1-0.3.5.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/PtjYWJkn/versions/0.3.5/sodium-extra-mc1.17.1-0.3.5.jar"
hash-format = "sha512"
hash = "df3fd147c28f55e11dedbabf4c1898de33c6d9590099c552a12f8ad181a233f9ed0860ffeb02b91eb8f8cd2c56dabedeb98e09412112f73fc82aa8a76a4f0e77"

[update]
[update.modrinth]
mod-id = "PtjYWJkn"
version = "qGLCzjA2"
