name = "Sodium"
filename = "sodium-fabric-mc1.17.1-0.3.0+build.5.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/AANobbMI/versions/mc1.17.1-0.3.0/sodium-fabric-mc1.17.1-0.3.0+build.5.jar"
hash-format = "sha512"
hash = "000d00496ed4e945c4d8c4d6b70584ffec5af6034c39e22d3ccc69734ccaadd37e7e9d31129da84c82d08798416a1a8daaf305656fa46406738a36505b7fd2e7"

[update]
[update.modrinth]
mod-id = "AANobbMI"
version = "1b0GhKHj"
